Update main.yml
I see this error on the upload_artifact step:
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run

Looking at the configuration of that step in main.yml here, I think there needs to be disambiguation between the Mac and Windows uploads. I think the breakage comes from changes in the upload-artifact v4 now not allowing matching names. I don't quite know what happened in the past since I don't have any old successful runs to compare with and confirm this guess, but that's my best idea at the moment. This explains a little more: https://github.com/actions/upload-artifact?tab=readme-ov-file#not-uploading-to-the-same-artifact 

Changing line 89 to be name: ${{ github.event.repository.name }}-${{ steps.short-sha.outputs.sha }}-${{ matrix.config }}-${{ matrix.os }} would be the first thing I would try.